services:
  face-analysis-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: face-analysis-api:latest
    container_name: face-analysis-api
    ports:
      - "8000:8000"
    volumes:
      # 模型檔案（唯讀）
      - ./model:/app/model:ro
      # 外部依賴（dlib, TopoFR）
      - ./external:/app/external:ro
      # 工作區（可讀寫）
      - ./workspace:/app/workspace
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
      # GPU 相關（有 GPU 時會自動使用）
      - CUDA_VISIBLE_DEVICES=0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '8.0'
          memory: 8G
        reservations:
          cpus: '2.0'
          memory: 4G
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]